package com.ISLab;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

public class SHA1 {
    /*
     * Name - Vishal Pandey
     * UID - 19BCS2930
     */
    public static String encryptThisString(String input)
    {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-1");

            byte[] messageDigest = md.digest(input.getBytes());

            BigInteger no = new BigInteger(1, messageDigest);

            String hashtext = no.toString(16);

            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }

            return hashtext;
        }

        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String[] args) throws NoSuchAlgorithmException{

        Scanner sc = new Scanner(System.in);
        System.out.println("HashCode Generated by SHA-1 for: ");

        System.out.print("\n Enter the String you want to Encrypt: ");
        String s1 = sc.nextLine();

        System.out.println("\nThe SHA-1 Code for string '" + s1 + "' is : " + encryptThisString(s1));

    }
}

